name: Build Sample
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew integrationTest
          api: 30
          tag: default
          abi: x86
