name: Build Sample
on: [pull_request]

jobs:

  instrumentationTests:
    name: Screenshot Tests
    runs-on: macos-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Test build
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          profile: pixel_3a
          script: ./run-tests.sh